export const BALANCE = {
  PALADIN: {
    HEAL_COST: 40,
    HEAL_AMOUNT: 90,
    HEAL_RADIUS: 180,
    SHIELD_COST: 35,
    SHIELD_AMOUNT: 120,
    FLASH_COST: 45,
    FLASH_HEAL: 70,
    FLASH_DAMAGE: 60,
    FLASH_RADIUS: 200
  },
  ROGUE: {
    SPRINT_COST: 25,
    SPRINT_SPEED: 2.5,
    WHIRL_COST: 40,
    WHIRL_DAMAGE: 70,
    WHIRL_RADIUS: 180,
    SHADOW_COST: 55,
    SHADOW_DAMAGE: 50,
    SHADOW_SLOW: 3.5,
    SHADOW_RADIUS: 220
  },
  ARCHMAGE: {
    BLAST_COST: 35,
    BLAST_DAMAGE: 80,
    BLAST_RADIUS: 120,
    ELEMENTAL_COST: 60,
    ELEMENTAL_HP: 200,
    ELEMENTAL_DPS: 18,
    ELEMENTAL_RANGE: 210,
    ELEMENTAL_DURATION: 20,
    DEMON_COST: 90,
    DEMON_HP: 500,
    DEMON_DPS: 36,
    DEMON_RANGE: 60,
    DEMON_DURATION: 25
  },
  FIRE_AURA: {
    RADIUS: 100,
    DPS_PER_TICK: 10,
    TICK_MS: 1000,
    DURATION_MS: 20000
  }
};

export default BALANCE;
